### ISSUE TITLE
Can you provide the datasets in the probability-baselines.ipynb file?

### ISSUE THREAD

**Issue by Moximixi** [potsawee/selfcheckgpt#18]
![image](https://github.com/potsawee/selfcheckgpt/assets/32200567/c041bcab-afc7-484c-91ca-1f1a860d3bd6)
I can't find the data sets for these two parts, so I can't run the following code at all. Could you please provide it? Thank you very much!

**Comment by potsawee** [comment]
Hi @Moximixi ,

I've edited the notebook so that you can get examples IDs from the HF dataset as well as providing the link to download cache file (at https://drive.google.com/file/d/1t3pJt0o395rdPHK6h6S3s0bxnscQGzK0/view?usp=drive_link). Please check the notebook on github for the changes.

**Comment by Moximixi** [comment]
Thank you very much for your prompt reply!
