### ISSUE TITLE
When I run the latest version of 'probability-baselines.ipynb', there is an error. Could you please provide the full version number of the experimental environment?

### ISSUE THREAD

**Issue by Moximixi** [potsawee/selfcheckgpt#19]
When I run the code below：
![image](https://github.com/potsawee/selfcheckgpt/assets/32200567/dde0c4b1-baef-4556-be52-9bec66f1b5c6)
The error message is below. I don't know what the reason is, but I guess it might be a version issue with ‘openai’.
![image](https://github.com/potsawee/selfcheckgpt/assets/32200567/62b77aa6-c2b2-4053-bbbd-d79e89180f3c)

The relevant version numbers of my lab environment are as follows:
python               3.8.18
typing_extensions             4.8.0
openai                        1.2.4

**Comment by Moximixi** [comment]
I guess it might be better to provide 'requirements.txt'.

**Comment by Rcrossmeister** [comment]
I had the same problem. Looking forward to a requirements.txt

**Comment by Rcrossmeister** [comment]
Hi, I solved this problem by reinstalling openai 0.28.1, and my Python version is 3.9.12.

**Comment by Moximixi** [comment]
Setting the openai version to 0.28.1 worked, thanks!
