### ISSUE TITLE
about passage-level human annotations

### ISSUE THREAD

**Issue by 141forever** [potsawee/selfcheckgpt#21]
could you show us the human annotation score result of each passage? (which is used to calculate the Pearson and Spearman)

**Comment by potsawee** [comment]
Hi @141forever 

To obtain the passage-level score, we simply took the average of sentence-level scores, e.g., using `np.mean()`. We didn't perform weighting or anything extra.

**Comment by potsawee** [comment]
To obtain the sentence-level score from labels, you can use the following mapping `{"major_inaccurate": 1.0, "minor_inaccurate": 0.5, "accurate": 0.0}`

**Comment by 141forever** [comment]
thanks a lot! best wishes!
