### ISSUE TITLE
Could you provide a example of showing the AUC-PR of your own methods(i.e. the selfcheckgpt) just like the probability-based-baselines?

### ISSUE THREAD

**Issue by goatyu3** [potsawee/selfcheckgpt#32]
Hi there! Thanks for your awesome works.
Just like what i said in the title:Could you provide a example of showing the AUC-PR of your own methods(i.e. the selfcheckgpt) just like the probability-based-baselines?

**Comment by potsawee** [comment]
Hi @goatyu3 

thanks for trying the selfcheckgpt repository! I've added a notebook to show an example of SelfCheckGPT on WikiBio like the one with probability-based baselines. You can find it in the link below.

https://github.com/potsawee/selfcheckgpt/blob/main/demo/experiments/selfcheckgpt-nli-on-wikibio.ipynb

**Comment by goatyu3** [comment]
@potsawee Thank you for your reply. I will have a look.
