### ISSUE TITLE
Dataset construction

### ISSUE THREAD

**Issue by bravelyi** [potsawee/selfcheckgpt#34]
hello
1, I would like to know how to go about sorting the paragraphs in the process of creating the dataset, the raw data does not have all the sentences, do I need to crawl the data myself.
2, gpt3_text is generated by wiki_bio_text consisting of content via GPT3 via prompt, how is gpt3_text_samples generated? Is there any reference material about your dataset construction?

**Comment by potsawee** [comment]
hi @bravelyi

1. I downloaded the WikiBio dataset directly from HuggingFace without crawling anything further (e.g., using `load_dataset("wiki_bio")['test']`. I agree that there might be entities where not all sentences are there (like if there is some update on its actual Wikipedia page). But I don't think this is a problem at least for the experiments I conducted.

2. `gpt3_text` was generated with temperature = 0.0 (no sampling) while `gpt3_text_samples` were generated with temperature = 1.0 (sampling). The prompt was identical in both settings.

Hope this clarifies your questions!

**Comment by bravelyi** [comment]
"using the prompt "This is a Wikipedia passage about {concept}:".
 so only need to change the temperature of the gpt, the prompt is the above sentence, the content of the concept is the wikibio dataset inside the text, I probably understand what you mean, thank you very much!

**Comment by potsawee** [comment]
Yes that's correct, although some modifications that you could do if you work with modern models (say Llama3) would be:

1. The prompt is to `write an article in a Wikipedia style about {concept} with {attributes}`. This is more aligned with how people use Instruct models nowadays. (When I started this project, many models were still just pre-trained models, so I used next word prediction prompt style
2. Temperature: You could try using a lower temperature perhaps around 0.8. I found that modern models.

**Comment by bravelyi** [comment]
Thank you very much for your positive response, hats off!
