### ISSUE TITLE
code for proxy model

### ISSUE THREAD

**Issue by zthang** [potsawee/selfcheckgpt#5]
Hello~ Could you please upload your code for llama proxy model results? many thanks!

**Comment by potsawee** [comment]
Sorry for the delay. Sure, I will upload the code for proxy llm experiments this week.

**Comment by potsawee** [comment]
I added a script to LLaMA as a proxy LLM method in the following directory: 

https://github.com/potsawee/selfcheckgpt/tree/main/demo/experiments/proxy_model
